### ISSUE TITLE
Is this supported

### ISSUE THREAD

**Issue by superfan321** [sealingtech/wifi-ctf#1]
I continue to get several errors when trying to start the docker and building the docker. 

For example no such container: ctf

unable to find image 'ctf-kali:latest' locally

**Comment by jeremysolt** [comment]
It looks like there were some changes to one of the tools that we build and include inside the docker container (wacker) that would have caused the Dockerfile build to fail. If the image failed to build, the start script would fail to find the image. I've merged a fix.

Try rebuilding the image with
`docker build -t ctf-kali -f build/Dockerfile .
`
If that succeeds, you should be able to run the start.sh script to bring everything up.
Note: The default configuration is expecting 2 network interfaces and you'll want to make sure the correct interface names are set in start.sh

**Comment by superfan321** [comment]
Thanks for the response I ended up rebuilding the script and the docker image it is working great thank you so much again for the reply and the idea. its really fun being able to do this without having to set up all the access points.
